graceTimeOut = 10
debug = false
checkNewVersion = true
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
OnHostRule = true

[retry]
attempts = 2

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
usebindportip = false
swarmmode = false

